version: '3'  # Define the version of the Docker Compose file format

services:
  db:
    image: postgres:13  # Use the official PostgreSQL image
    restart: always  # Always restart the container if it stops
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}  # Database name from .env
      POSTGRES_USER: ${POSTGRES_USER}  # Database user from .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Database password from .env

  web:
    build: .  # Build the web service from the current directory
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"  # Run migrations and start the server
    volumes:
      - .:/code  # Mount the current directory to /code in the container
    ports:
      - "8000:8000"  # Expose port 8000
    depends_on:
      - db  # Ensure the db service is started before the web service
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

volumes:
  postgres_data:  # Define a named volume for persisting PostgreSQL data
